[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
global = {path="../global"}
config = {path="../config"}
controller = {path="../controller"}
sea-orm = { version = "1.1.3",features = [ "sqlx-mysql", "runtime-async-std-native-tls", "macros" ] }
sea-orm-migration = "1.1.3"
