[package]
name = "logx"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-log = "0.2.0"
tracing-subscriber = {version = "0.3.19",features =["json"]}