[package]
name = "dbs"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.3",features = [ "sqlx-mysql", "runtime-async-std-native-tls", "macros" ] }
sea-orm-migration = "1.1.3"
serde = "*"